# Ensure to create the required directories before you run docker compose up
#  mkdir -p db-data redis-queue-data sites logs apps

version: "3.8"  # Updated to 3.8 for better health check support

services:
  backend:
    image: frappe/erpnext:v15.67.0
    networks:
      - frappe_network
    depends_on:
      create-site:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: frappe/erpnext:v15.67.0
    networks:
      - frappe_network
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - |
        # Wait for services to be ready
        wait-for-it -t 60 db:3306
        wait-for-it -t 60 redis-cache:6379
        wait-for-it -t 60 redis-queue:6379
        
        echo "Setting up bench configuration..."
        ls -1 apps > sites/apps.txt
        bench set-config -g db_host $$DB_HOST
        bench set-config -gp db_port $$DB_PORT
        bench set-config -g redis_cache "redis://$$REDIS_CACHE"
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE"
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"
        bench set-config -gp socketio_port $$SOCKETIO_PORT
        
        echo "Configuration completed successfully"
        echo "Final config check:"
        cat sites/common_site_config.json
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps

  create-site:
    image: frappe/erpnext:v15.67.0
    networks:
      - frappe_network
    depends_on:
      configurator:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps
    entrypoint:
      - bash
      - -c
    command:
      - |
        echo "Waiting for dependencies..."
        wait-for-it -t 120 db:3306
        wait-for-it -t 120 redis-cache:6379
        wait-for-it -t 120 redis-queue:6379
        
        # Verify config file exists and has required keys
        if [ ! -f sites/common_site_config.json ]; then
          echo "ERROR: common_site_config.json not found!"
          exit 1
        fi
        
        echo "Configuration file found, contents:"
        cat sites/common_site_config.json
        
        echo "Creating ERPNext site..."
        bench new-site frontend \
          --mariadb-user-host-login-scope='%' \
          --admin-password=admin \
          --db-root-username=root \
          --db-root-password=admin \
          --install-app erpnext \
          --set-default
        
        echo "Site creation completed successfully!"

  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=admin", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: frappe/erpnext:v15.67.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps
      - ./frappe_multi.conf:/etc/nginx/conf.d/frappe_multi.conf
    ports:
      - "0.0.0.0:8090:8080"
      - "0.0.0.0:8092:8092"

  queue-long:
    image: frappe/erpnext:v15.67.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps

  queue-short:
    image: frappe/erpnext:v15.67.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure

  scheduler:
    image: frappe/erpnext:v15.67.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps

  websocket:
    image: frappe/erpnext:v15.67.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/Documents/frappe_docker/db-data
  redis-queue-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/Documents/frappe_docker/redis-queue-data
  sites:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/Documents/frappe_docker/sites
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/Documents/frappe_docker/logs
  apps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/administrator/Documents/frappe_docker/apps

networks:
  frappe_network:
    driver: bridge
